name: carenet-front CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      # 1. 저장소의 코드를 가져오기
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Node.js 환경 설정
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Ensure dist directory permissions
        run: |
          mkdir -p ./dist
          chmod 777 ./dist

      # 3. Vite 프로젝트 빌드
      - name: Install dependencies and build
        run: |
          npm install
          npm run build

      - name: Fix dist directory permissions after build
        run: |
          echo pwd
          chmod -R 777 ./dist

      # 6. SSH key 설정 및 파일 전송
      - name: ssh key with passphrase
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          passphrase: ${{ secrets.PASSPHRASE }}
          port: ${{ secrets.PORT }}
          source: "./dist"
          target: ${{ secrets.REMOTE_PATH }}
